"""empty message

Revision ID: 33a67e7296eb
Revises: a0315fe435be
Create Date: 2020-03-22 01:08:21.072073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33a67e7296eb'
down_revision = 'a0315fe435be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('first_name', sa.String(length=40), nullable=True))
    op.add_column('user', sa.Column('image', sa.String(length=200), nullable=True))
    op.add_column('user', sa.Column('last_name', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'image')
    op.drop_column('user', 'first_name')
    # ### end Alembic commands ###
